---
driver:
  name: docker
  hostname: neutron.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: <%=ENV['SALT_VERSION'] || 'latest'%>
  require_chef: false
  log_level: error
  formula: neutron
  grains:
    noservices: True
  vendor_repo:
    - type: apt
      url: http://apt-mk.mirantis.com/trusty
      key_url: http://apt-mk.mirantis.com/public.gpg
      components: oc303 extra
      distribution: nightly
  dependencies:
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux
    - name: keystone
      repo: git
      source: https://github.com/salt-formulas/salt-formula-keystone
  state_top:
    base:
      "*":
        - linux.system
        - neutron
  pillars:
    top.sls:
      base:
        "*":
          - linux_repo_openstack
          - neutron
  pillars-from-files:
    linux_repo_openstack.sls: tests/pillar/repo_mos9.sls

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%=ENV['PLATFORM'] || 'saltstack-ubuntu-xenial-salt-stable'%>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:

  - name: compute_dpdk
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/compute_dpdk.sls

  - name: compute_dvr
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/compute_dvr.sls

  - name: compute_dvr_fwaas_v1
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/compute_dvr_fwaas_v1.sls

  - name: compute_legacy
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/compute_legacy.sls

  - name: compute_nonexternal_dvr
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/compute_nonexternal_dvr.sls

  - name: compute_sriov
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/compute_sriov.sls

  - name: compute_qos_sriov
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/compute_qos_sriov.sls

  - name: compute_qos
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/compute_qos.sls

  - name: compute_ovn
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/compute_ovn.sls

  - name: compute_bgpvpn
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/compute_bgpvpn.sls

  - name: control_cluster
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/control_cluster.sls

  - name: control_dvr
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/control_dvr.sls

  - name: control_nodvr
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/control_nodvr.sls

  - name: control_lbaas_octavia
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/control_lbaas_octavia.sls

  - name: control_fwaas_v1
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/control_fwaas_v1.sls

  - name: control_l2gw
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/control_l2gw.sls

  - name: control_opendaylight
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/control_opendaylight.sls

  - name: control_single
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/control_single.sls

  - name: control_qos
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/control_qos.sls

  - name: control_ovn
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/control_ovn.sls

  - name: control_bgpvpn
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/control_bgpvpn.sls

  - name: gateway_dvr
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/gateway_dvr.sls

  - name: gateway_legacy
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/gateway_legacy.sls

  - name: gateway_qos
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/gateway_qos.sls

  - name: gateway_legacy_fwaas_v1
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/gateway_legacy_fwaas_v1.sls

  - name: gateway_legacy_l2gw
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/gateway_legacy_l2gw.sls

  - name: gateway_legacy_opendaylight
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/gateway_legacy_opendaylight.sls

  - name: control_dns
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/control_dns.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
